version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
      - "2345:2345"
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  filter:
    build:
      context: .
      dockerfile: Dockerfile.dev

    env_file:
      - development.env

    depends_on:
      rabbitmq:
        condition: service_started
      redis:
        condition: service_healthy   

    volumes:
      # Código do go_rabbitMq_filter
      - .:/app

      # GO_RabbitMqHandler local
      - ../GO_RabbitMqHandler:/GO_RabbitMqHandler

      # Cache do Go
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build

    container_name: app_filter

    ports:
      - "8080:8080"

    stdin_open: true
    tty: true
    
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      
volumes:
  go-mod-cache:
  go-build-cache:
  rabbitmq_data:
  redis_data: