version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  filter:
    build:
      context: .
      dockerfile: Dockerfile.dev

    env_file:
      - development.env

    depends_on:
      rabbitmq:
        condition: service_started

    volumes:
      # Código do go_rabbitMq_filter
      - .:/app

      # GO_RabbitMqHandler local
      - ../GO_RabbitMqHandler:/GO_RabbitMqHandler

      # Cache do Go
      - go-mod-cache:/go/pkg/mod
      - go-build-cache:/root/.cache/go-build

    container_name: app_filter

    ports:
      - "8080:8080"

    stdin_open: true
    tty: true

volumes:
  go-mod-cache:
  go-build-cache:
  rabbitmq_data: