name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
  
permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build CI Image
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GO_PERSONAL_CLUSTER_ACTOR }}
          password: ${{ secrets.GO_PERSONAL_CLUSTER_TOKEN }}

      - name: Set image name
        id: image
        run: |
          echo "name=ghcr.io/${GITHUB_REPOSITORY,,}/ci:${GITHUB_SHA}" >> "$GITHUB_OUTPUT"

      - name: Execute Integration Tests
        run: |
          docker build \
            -f Dockerfile.ci \
            -t ${{ steps.image.outputs.name }} \
            .

      - name: Push CI image
        run: |
          docker push ${{ steps.image.outputs.name }}

      - name: Upload Kubernetes Job manifest
        uses: actions/upload-artifact@v4
        with:
          name: kubernetes-ci-manifest
          path: k8s/ci-job.yaml