name: RabbitMQ Handler CI

on:
  push:
    branches:
      - main

  workflow_run:
    workflows:
      - Build
    types:
      - completed

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gopersonalcluster/go-rabbitmq-filter

jobs:
  deploy:
    name: Deploy Golang app
    runs-on: ubuntu-latest

    # Não faz deploy se o workflow Build terminou com erro
    if: >
      github.event_name == 'push' ||
      github.event.workflow_run.conclusion == 'success'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GO_PERSONAL_CLUSTER_ACTOR }}
          password: ${{ secrets.GO_PERSONAL_CLUSTER_TOKEN }}
      # Nome EXATO do package no GHCR:
      # ghcr.io/gopersonalcluster/go-rabbitmq-filter/go-rabbitmq-filter
      - name: Definir imagem
        run: |
          echo "IMAGE=ghcr.io/gopersonalcluster/go-rabbitmq-filter" >> "$GITHUB_ENV"
          echo "IMAGE_TAG=${{ github.sha }}" >> "$GITHUB_ENV"
      

           
      - name: Build Docker image
        run: |
          docker build \
            -t "${IMAGE}:${IMAGE_TAG}" \
            -t "${IMAGE}:latest" \
            .

      - name: Push Docker image
        run: |
          docker push "${IMAGE}:${IMAGE_TAG}"
          docker push "${IMAGE}:latest"


      - name: Build Image
        run: |
          docker build \
            -t "${IMAGE}:${IMAGE_TAG}" \
            -t "${IMAGE}:latest" \
            .

      - name: Push Image
        run: |
          docker push "${IMAGE}:${IMAGE_TAG}"
          docker push "${IMAGE}:latest"

      - name: Configurar kubeconfig
        run: |
          mkdir -p ~/.kube

          printf '%s' '${{ secrets.KUBE_CONFIG }}' > ~/.kube/config

          chmod 600 ~/.kube/config

          echo "Validando kubeconfig..."

          kubectl config current-context
          kubectl cluster-info
          kubectl get namespaces

      - name: Mostrar namespace.yaml
        run: |
          echo "========== namespace.yaml =========="
          cat k8s/namespace.yaml
          echo "===================================="

      - name: Aplicar Kubernetes
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Atualizar imagem
        run: |
          echo "Atualizando Deployment..."

          kubectl -n ci set image deployment/go-rabbitmq-filter \
            go-rabbitmq-filter=ghcr.io/gopersonalcluster/go-rabbitmq-filter:latest

      - name: Verificar imagem configurada
        run: |
          kubectl -n ci get deployment go-rabbitmq-filter \
            -o jsonpath='{.spec.template.spec.containers[0].image}' 

          echo

      - name: Aguardar Deployment
        run: |
          kubectl rollout status deployment/go-rabbitmq-filter \
            -n ci \
            --timeout=10m

      - name: Verificar Pods
        run: |
          kubectl get pods -n ci -o wide