info:
  contact: {}
paths:
  /healthCheck:
    get:
      description: smoke test
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      tags:
      - test
swagger: "2.0"
